      - id: check-double-quotes
        name: Check double quotes in YAML configmap section
        entry: check-double-quotes
        language: python
        files: '^.*\.ya?ml$'
        types: [file]
